export const SORT_REPOS_BY = 'SORT_REPOS_BY';
export const FETCH_REPO_DETAILS_ERROR = 'FETCH_REPO_DETAILS_ERROR';
export const FETCH_REPO_DETAILS_SUCCESS = 'FETCH_REPO_DETAILS_SUCCESS';
export const FETCH_REPO_DETAILS_PENDING = 'FETCH_REPO_DETAILS_PENDING';
export const FETCH_REPOS_PENDING = 'FETCH_REPOS_PENDING';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_ERROR = 'FETCH_REPOS_ERROR';